rag_task:
  description: >
    Answer questions based on the provided query. Find the most relevant information
    from the financial data. You might need to generate the query to find the
    most relevant information from the vector database.
    This is the query: {query}
  expected_output: >
    The answer to the relevant question: {query}
  agent: rag_agent

graph_generation_task:
  description: >
    Generate a graph based on the data generating trends from the data.
    Use python, matplotlib to generate the graphs.
  expected_output: >
    Python code that can be executed to generate the output which consists of a graph report.
    The output file should be a valid python file.
  agent: graph_generation_agent
  output_file: "outputs/report.ipynb"

report_for_stakeholders_task:
  description: >
    Take the output of the reporting analyst agent and write a report for the stakeholders.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formatted as markdown without '```'
  agent: report_for_stakeholders_agent
  output_file: "outputs/q4_report.md"
